name: computo-publish

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore artifact
        uses: actions/download-artifact@v4
        with: 
          name: artifact-env
          path: ${{ runner.temp }}/

      - name: Activate the environment from the cache with the script in the artifact
        id: activate-env
        run: source ${{ runner.temp }}/activate_env.sh

      - name: Restore Cache environment
        uses: actions/cache@v4
        with:
          fail-on-cache-miss: true
          path: |
            ${{ fromJson(steps.activate-env.outputs.cache-path) }}
          key: ${{ steps.activate-env.outputs.key }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake libcairo2-dev libfontconfig1-dev libfreetype6-dev pandoc libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
      
      - name: run any post-setup commands from setup-render-ci.sh
        run: |
          if [[ -f setup-render-ci.sh ]]; then
            bash setup-render-ci.sh
          fi

      - name: Install Computo extension for Quarto
        run: |
          if [[ ! -f .nocomputo ]]; then
            quarto add --no-prompt computorg/computo-quarto-extension
          fi

      - name: Render
        run: |
          quarto render --output-dir=public
          if [[ ! -f ./public/index.html ]]; then
            echo "No index.html found in public directory. copying the first HTML file."
            cp $(ls ./public/*.html | head -n 1) ./public/index.html
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    # skip this job if the event that triggered the workflow is a pull request
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
